"""
IMPORTANT REMINDER TO ME: 
    THIS PROGRAM IS MEANT TO RUN ON A MACHINE WITHOUT GENERAL ACCESS
    **DO NOT** RUN IF A LOT OF PEOPLE CAN ACCESS THE SECRET KEY ON THE DEVICE
    POSSIBLY COULD LEAD TO TO STEALING OF CLIENT ID/SECRET
"""
